### ISSUE TITLE
Switch from emma to jacoco for code coverage

### ISSUE THREAD

**Issue by jentfoo** [threadly/litesockets#15]
In order to be compiled with java 8, we can no longer use emma.  We have to switch to jacoco.  I just made this change on threadly's unstable_staging branch (4.0.0-SNAPSHOT).  I personally like emma better, but it's a change we are going to have to make.

Because I have to change the code base and jenkins at the same time, I prefer to do this directly in master.  There is no rush, we just have to do this once we want to support compiling with java 8.

So with that said, Luke would you comment on this issue when you want me to do the switch.  You can look at jenkins for unstable_staging or ambush as both those have been switched over now.

**Comment by lwahlmeier** [comment]
done with 2.0.0 release
