### ISSUE TITLE
Make UDPServer packet buffer size configurable

### ISSUE THREAD

**Issue by Xorlev** [threadly/litesockets#30]
In [UDPServer.java#L75](https://github.com/threadly/litesockets/blob/6a9d7bb8892c105cb075fa989dee9435fb13ee37/src/main/java/org/threadly/litesockets/udp/UDPServer.java#L75), the bytebuffer allocated is always 1500 bytes. Practically, 1500 bytes should almost always be enough, but some environments are configured to use jumbo frames.

**Comment by lwahlmeier** [comment]
Very good idea, I will mark this as an enhancement and try to get it in with the next release.  I am going to be adding a generic way to pass in options to Clients.

**Comment by lwahlmeier** [comment]
this has been added in the new 3.0.0 version of litesockets.
