### ISSUE TITLE
Rename SocketExecuter to SocketExecutor

### ISSUE THREAD

**Issue by jentfoo** [threadly/litesockets#45]
SocketExecutor would closer match other java `Executor` language.  This would be a change for 4.X

**Comment by lwahlmeier** [comment]
I completely disagree.  "ter" was deliberate, not a mistake, and I do not like the "tor" spelling.  This is also no a thread Executor so I see no reason to stick to it, what I see as bad naming.

**Comment by jentfoo** [comment]
Fair enough, just 9/10 I find myself typing the wrong one due to muscle memory.
